### PR TITLE
remove storage dependency

### PR DESCRIPTION
**Pull request by jpihl**
I've removed the storage dependency and fixed a few bugs.

This way it's more likely that the library is useful for other people.

@mortenvp @petya2164 @looopTools any comments?

### CODE REVIEW

**Comment by petya2164** [comment]
@jpihl This is a great change! I think we are overusing storage at many places...

**Comment by petya2164** [comment]
I fixed the issue with the missing include files and added config.py.
We can merge this soon.

**Comment by petya2164** [comment]
I noticed that the buildbot status user was not authorized to post the status for this repo, so I added the team and we have the green tick now ;)

**Comment by mortenvp** [comment]
Looks good. What were the bugs - I could not see anything obvious from the pull-request?

**Comment by jpihl** [comment]
What I meant by "bugs" was typos in some of the text files, i.e. condian(?) to hex, and storage to hex.
Thanks for fixing the includes Peter. I'll merge and release this bad boy now.

**Pull request merged**
